language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - cd colaboradores-api/
  - echo "Let's start Maven Package!!!"
  - mvn clean package
  - cd ..
  - echo "We are in root dir"
script:
  - docker-compose build
before_deploy:
  - echo "Fordk@2021" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag colaboradores-api:latest $DOCKER_USERNAME/colaboradores-api:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/colaboradores-api;
  on:
    branch: master
notifications:
  email: false