language: java
jdk:
    - openjdk17
before_install:
    - sudo apt-get update
    - cd /colaboradores-api
    - echo "Let's start Maven Package!!!"
    - mvn clean package
    - cd ..
    - echo "We are in root dir"
script:
    - docker-compose build
before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
    provider: script
    script:
        docker push dione2508/colaboradores-api;
    on:
        branch: master
notifications:
    email: false