name: 'Colaboradores CI'

on:

  push:
    branches:
      - master
    paths:
      - colaboradores-api/**
  pull_request: # [master, next]
    paths:
      - colaboradores-api/**

jobs:

  colaboradores:
    name: 'Colaboradores API'
    runs-on: ubuntu-latest

    # Use the Bash sehll regardless whether th GitHub Actions
    defaults:
      run:
        working-directory: colaboradores-api
        shell: bash
    
    steps:

    - if: github.event_name == 'push_request'
      name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Check Out Repo
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      if: github.event_name == 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      if: github.event_name == 'pull_request'
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      if: github.event_name == 'pull_request'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./colaboradores-api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/colaboradores:${{ steps.buildnumber.outputs.build_number }}


